version: '3.8'

services:
  web:
    image: docgeograph/homework_django:latest
    # build:
    #   context: ./djangodock
    #   dockerfile: Dockerfile
    container_name: djangodock
    command: gunicorn djangodock.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    image: docgeograph/homework_nginx:latest
    # build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: